name: 'Kivy App to APK'
description: 'Convert Kivy app to APK'

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Hardcoded Python version

      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash

      - name: Prepare virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo "Using Python==$(python --version)"
        shell: bash
      
      - name: Install and upgrade dependencies
        run: |
          sudo apt update
          sudo apt install -y git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev
          export PATH=$PATH:~/.local/bin/
          python3 -m pip install --upgrade Cython==0.29.33 buildozer
        shell: bash

      - name: Install requirements if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi
        shell: bash

      - name: Build with Buildozer
        run: buildozer android debug
        shell: bash
